Add Droplet Stuff
open-realms/command-block pull request #6
Opened 2021-04-15 20:50 UTC by andrewgwoodruff

This MR adds the various DigitalOcean droplet routes, utilizing the open-realms/do-minecraft library. This addresses https://github.com/open-realms/command-block/issues/2.

2021-04-15 21:09 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  createDroplet(): string {
```suggestion
  async createDroplet(): string {
```

2021-04-15 21:23 UTC, johnbwoodruff requested changes

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  createDroplet(): string {
```suggestion
  async createDroplet(): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +    return this.dropletService.createDroplet();
```suggestion
    return await this.dropletService.createDroplet();
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  deleteDroplet(@Param() params): string {
```suggestion
  async deleteDroplet(@Param() params): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +    return this.dropletService.deleteDroplet(params.id);
```suggestion
    return await this.dropletService.deleteDroplet(params.id);
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  getDropletDetails(@Param() params): string {
```suggestion
  async getDropletDetails(@Param() params): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +    return this.dropletService.getDropletDetails(params.id);
```suggestion
    return await this.dropletService.getDropletDetails(params.id);
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  updateDropletDetails(@Param() params): string {
```suggestion
  async updateDropletDetails(@Param() params): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +    return this.dropletService.updateDropletDetails(params.id);
```suggestion
    return await this.dropletService.updateDropletDetails(params.id);
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  startDroplet(@Param() params): string {
```suggestion
  async startDroplet(@Param() params): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +    return this.dropletService.startDroplet(params.id);
```suggestion
    return await this.dropletService.startDroplet(params.id);
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +  stopDroplet(@Param() params): string {
```suggestion
  async stopDroplet(@Param() params): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.ts
> +    return this.dropletService.stopDroplet(params.id);
```suggestion
    return await this.dropletService.stopDroplet(params.id);
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  getAllDroplets(): string {
```suggestion
  async getAllDroplets(): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  createDroplet(): string {
```suggestion
  async createDroplet(): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  deleteDroplet(id: string): string {
```suggestion
  async deleteDroplet(id: string): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  getDropletDetails(id: string): string {
```suggestion
  async getDropletDetails(id: string): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  updateDropletDetails(id: string): string {
```suggestion
  async updateDropletDetails(id: string): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  startDroplet(id: string): string {
```suggestion
  async startDroplet(id: string): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.service.ts
> +  stopDroplet(id: string): string {
```suggestion
  async stopDroplet(id: string): string {
```

2021-04-15 21:23 UTC, johnbwoodruff commented on src/droplet/droplet.controller.spec.ts
> +describe('DropletController', () => {
I'd love for us to start out doing tests from the beginning of this project.

2021-04-20 03:35 UTC, andrewgwoodruff commented
Just to make sure I understand, the `:id/start` and `:id/stop` PUT endpoints are just abstractions as far as the frontend is concerned, yes? Like an end user will have the option to `stop` their world, and when they click that button, what actually happens on the backend is that we spin down the server, take a snapshot, and kill the DigitalOcean droplet. Is that correct? Likewise, when the end-user hits the `start world` button, it does a PUT request to the `:id/start` endpoint, which fetches the existing snapshot and uses that to create a new droplet with that snapshot. Does that reflect your expectation of how those two endpoints will work, John?

If so, that would mean that the DELETE `:id` endpoint goes and actually kills/deletes/destroys the whole droplet and doesn't save anything. Let me know if that's what you're going for.

2021-10-08 22:47 UTC, johnbwoodruff commented
Closed in favor of #10

2021-10-08 22:47 UTC, closed without merging